// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * ActionItemDraft
 */
export type ActionItemDraft = {
    /**
     * Description
     */
    description: string;
    priority?: TaskPriority;
    due_kind?: DueKind;
    /**
     * Due Phrase
     */
    due_phrase?: string | null;
    /**
     * Due At
     */
    due_at?: string | null;
    /**
     * Needs Review
     */
    needs_review?: boolean;
    /**
     * Review Reason
     */
    review_reason?: string | null;
    /**
     * Verbatim
     */
    verbatim?: string | null;
};

/**
 * Body_handovers-upload_handover
 */
export type Body_handovers_upload_handover = {
    /**
     * File
     */
    file: Blob | File;
    /**
     * Recorded At
     */
    recorded_at: string;
    /**
     * Shift Label
     */
    shift_label?: string | null;
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * DashboardHandoverStatus
 */
export type DashboardHandoverStatus = 'handed_over' | 'no_handover';

/**
 * DashboardPatientPublic
 */
export type DashboardPatientPublic = {
    patient: PatientPublic;
    handover_status: DashboardHandoverStatus;
    /**
     * Handover Id
     */
    handover_id: string | null;
    /**
     * Card Id
     */
    card_id: string | null;
    /**
     * Confirmed At
     */
    confirmed_at: string | null;
    illness_severity: IllnessSeverity;
    /**
     * Patient Summary
     */
    patient_summary: string | null;
    /**
     * Situation Awareness
     */
    situation_awareness: string | null;
    /**
     * Contingencies
     */
    contingencies: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Pending Results
     */
    pending_results: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Tasks
     */
    tasks: Array<TaskPublic>;
    /**
     * Flags
     */
    flags: Array<FlagPublic>;
    /**
     * Next Due At
     */
    next_due_at: string | null;
};

/**
 * DashboardPublic
 */
export type DashboardPublic = {
    /**
     * Generated At
     */
    generated_at: string;
    /**
     * Patients
     */
    patients: Array<DashboardPatientPublic>;
};

/**
 * DemoAccess
 */
export type DemoAccess = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * DocumentReferencePublic
 */
export type DocumentReferencePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Handover Id
     */
    handover_id: string;
    /**
     * Patient Id
     */
    patient_id: string | null;
    type: DocumentType;
    /**
     * Content Type
     */
    content_type: string;
    /**
     * Size Bytes
     */
    size_bytes: number | null;
    /**
     * Author Id
     */
    author_id: string;
    /**
     * Authored At
     */
    authored_at: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * DocumentType
 */
export type DocumentType = 'audio' | 'transcript' | 'extraction_json';

/**
 * DueKind
 */
export type DueKind = 'clock' | 'relative' | 'unspecified';

/**
 * FlagCategory
 */
export type FlagCategory = 'task_due_soon' | 'task_overdue' | 'unstable_patient';

/**
 * FlagPublic
 */
export type FlagPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Handover Id
     */
    handover_id: string;
    /**
     * Task Id
     */
    task_id: string | null;
    category: FlagCategory;
    status: FlagStatus;
    /**
     * Fire At
     */
    fire_at: string;
    /**
     * Fired At
     */
    fired_at: string | null;
    /**
     * Acknowledged By Id
     */
    acknowledged_by_id: string | null;
    /**
     * Acknowledged At
     */
    acknowledged_at: string | null;
};

/**
 * FlagStatus
 */
export type FlagStatus = 'active' | 'inactive';

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HandoverDetailPublic
 */
export type HandoverDetailPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Author Id
     */
    author_id: string;
    status: HandoverStatus;
    /**
     * Recorded At
     */
    recorded_at: string;
    /**
     * Shift Label
     */
    shift_label: string | null;
    /**
     * Audio Content Type
     */
    audio_content_type: string;
    /**
     * Transcript Text
     */
    transcript_text: string | null;
    /**
     * Attempts
     */
    attempts: number;
    /**
     * Last Error
     */
    last_error: string | null;
    /**
     * Confirmed At
     */
    confirmed_at: string | null;
    /**
     * Confirmed By Id
     */
    confirmed_by_id: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Patients
     */
    patients: Array<HandoverPatientPublic>;
};

/**
 * HandoverPatientPublic
 */
export type HandoverPatientPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Handover Id
     */
    handover_id: string;
    /**
     * Patient Id
     */
    patient_id: string | null;
    /**
     * Order Index
     */
    order_index: number;
    /**
     * Mention Verbatim
     */
    mention_verbatim: string;
    match_status: MatchStatus;
    /**
     * Match Candidates
     */
    match_candidates: Array<MatchCandidatePublic>;
    illness_severity: IllnessSeverity;
    /**
     * Severity Evidence
     */
    severity_evidence: string | null;
    /**
     * Patient Summary
     */
    patient_summary: string | null;
    /**
     * Situation Awareness
     */
    situation_awareness: string | null;
    /**
     * Contingencies
     */
    contingencies: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Pending Results
     */
    pending_results: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Action Items
     */
    action_items: Array<ActionItemDraft>;
    /**
     * Transcript Excerpt
     */
    transcript_excerpt: string | null;
    /**
     * Edited By Doctor
     */
    edited_by_doctor: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * HandoverPatientUpdate
 */
export type HandoverPatientUpdate = {
    /**
     * Patient Id
     */
    patient_id?: string | null;
    illness_severity?: IllnessSeverity | null;
    /**
     * Patient Summary
     */
    patient_summary?: string | null;
    /**
     * Situation Awareness
     */
    situation_awareness?: string | null;
    /**
     * Contingencies
     */
    contingencies?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Pending Results
     */
    pending_results?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Action Items
     */
    action_items?: Array<ActionItemDraft> | null;
};

/**
 * HandoverPublic
 */
export type HandoverPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Author Id
     */
    author_id: string;
    status: HandoverStatus;
    /**
     * Recorded At
     */
    recorded_at: string;
    /**
     * Shift Label
     */
    shift_label: string | null;
    /**
     * Audio Content Type
     */
    audio_content_type: string;
    /**
     * Transcript Text
     */
    transcript_text: string | null;
    /**
     * Attempts
     */
    attempts: number;
    /**
     * Last Error
     */
    last_error: string | null;
    /**
     * Confirmed At
     */
    confirmed_at: string | null;
    /**
     * Confirmed By Id
     */
    confirmed_by_id: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * HandoverStatus
 */
export type HandoverStatus = 'uploaded' | 'transcribing' | 'extracting' | 'matching' | 'awaiting_review' | 'confirmed' | 'failed' | 'discarded';

/**
 * HandoversPublic
 */
export type HandoversPublic = {
    /**
     * Data
     */
    data: Array<HandoverPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * IllnessSeverity
 */
export type IllnessSeverity = 'stable' | 'watcher' | 'unstable' | 'unspecified';

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
    /**
     * Data
     */
    data: Array<ItemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * MatchCandidatePublic
 */
export type MatchCandidatePublic = {
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Reason
     */
    reason: string;
    /**
     * Score
     */
    score: number;
    /**
     * Family Name
     */
    family_name?: string | null;
    /**
     * Given Name
     */
    given_name?: string | null;
    /**
     * Bed
     */
    bed?: string | null;
    /**
     * Mrn
     */
    mrn?: string | null;
};

/**
 * MatchStatus
 */
export type MatchStatus = 'matched' | 'ambiguous' | 'unmatched' | 'doctor_resolved';

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PatientCreate
 */
export type PatientCreate = {
    /**
     * Mrn
     */
    mrn: string;
    /**
     * Family Name
     */
    family_name: string;
    /**
     * Given Name
     */
    given_name: string;
    /**
     * Birth Date
     */
    birth_date?: string | null;
    sex?: Sex;
    /**
     * Bed
     */
    bed?: string | null;
    /**
     * Unit
     */
    unit?: string | null;
    /**
     * Admitting Diagnosis
     */
    admitting_diagnosis?: string | null;
    /**
     * Attending Name
     */
    attending_name?: string | null;
    /**
     * Admitted At
     */
    admitted_at?: string | null;
    /**
     * Active
     */
    active?: boolean;
};

/**
 * PatientPublic
 */
export type PatientPublic = {
    /**
     * Mrn
     */
    mrn: string;
    /**
     * Family Name
     */
    family_name: string;
    /**
     * Given Name
     */
    given_name: string;
    /**
     * Birth Date
     */
    birth_date?: string | null;
    sex?: Sex;
    /**
     * Bed
     */
    bed?: string | null;
    /**
     * Unit
     */
    unit?: string | null;
    /**
     * Admitting Diagnosis
     */
    admitting_diagnosis?: string | null;
    /**
     * Attending Name
     */
    attending_name?: string | null;
    /**
     * Admitted At
     */
    admitted_at?: string | null;
    /**
     * Active
     */
    active?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * PatientRecordCardPublic
 */
export type PatientRecordCardPublic = {
    card: HandoverPatientPublic;
    /**
     * Handover Id
     */
    handover_id: string;
    /**
     * Author Id
     */
    author_id: string;
    /**
     * Recorded At
     */
    recorded_at: string;
    /**
     * Confirmed At
     */
    confirmed_at: string;
    /**
     * Shift Label
     */
    shift_label: string | null;
};

/**
 * PatientRecordPublic
 */
export type PatientRecordPublic = {
    patient: PatientPublic;
    /**
     * Cards
     */
    cards: Array<PatientRecordCardPublic>;
    /**
     * Tasks
     */
    tasks: Array<TaskPublic>;
    /**
     * Flags
     */
    flags: Array<FlagPublic>;
    /**
     * Documents
     */
    documents: Array<DocumentReferencePublic>;
};

/**
 * PatientUpdate
 */
export type PatientUpdate = {
    /**
     * Mrn
     */
    mrn?: string | null;
    /**
     * Family Name
     */
    family_name?: string | null;
    /**
     * Given Name
     */
    given_name?: string | null;
    /**
     * Birth Date
     */
    birth_date?: string | null;
    sex?: Sex | null;
    /**
     * Bed
     */
    bed?: string | null;
    /**
     * Unit
     */
    unit?: string | null;
    /**
     * Admitting Diagnosis
     */
    admitting_diagnosis?: string | null;
    /**
     * Attending Name
     */
    attending_name?: string | null;
    /**
     * Admitted At
     */
    admitted_at?: string | null;
    /**
     * Active
     */
    active?: boolean | null;
};

/**
 * PatientsPublic
 */
export type PatientsPublic = {
    /**
     * Data
     */
    data: Array<PatientPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * Sex
 */
export type Sex = 'male' | 'female' | 'other' | 'unknown';

/**
 * TaskCancel
 */
export type TaskCancel = {
    /**
     * Reason
     */
    reason: string;
};

/**
 * TaskPriority
 */
export type TaskPriority = 'routine' | 'urgent' | 'stat';

/**
 * TaskPublic
 */
export type TaskPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Handover Patient Id
     */
    handover_patient_id: string;
    /**
     * Handover Id
     */
    handover_id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Description
     */
    description: string;
    /**
     * Due At
     */
    due_at: string | null;
    due_kind: DueKind;
    /**
     * Due Phrase
     */
    due_phrase: string | null;
    priority: TaskPriority;
    status: TaskStatus;
    /**
     * Verbatim
     */
    verbatim: string | null;
    /**
     * Acknowledged By Id
     */
    acknowledged_by_id: string | null;
    /**
     * Acknowledged At
     */
    acknowledged_at: string | null;
    /**
     * Completed By Id
     */
    completed_by_id: string | null;
    /**
     * Completed At
     */
    completed_at: string | null;
    /**
     * Cancel Reason
     */
    cancel_reason: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * TaskStatus
 */
export type TaskStatus = 'requested' | 'accepted' | 'completed' | 'cancelled';

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    role?: UserRole;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    role?: UserRole;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserRole
 */
export type UserRole = 'doctor' | 'admin';

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    role?: UserRole | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type utilsDemoAccessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/demo-access/';
};

export type utilsDemoAccessResponses = {
    /**
     * Response Utils-Demo Access
     *
     * Successful Response
     */
    200: DemoAccess | null;
};

export type utilsDemoAccessResponse = utilsDemoAccessResponses[keyof utilsDemoAccessResponses];

export type itemsReadItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/items/';
};

export type itemsReadItemsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemsError = itemsReadItemsErrors[keyof itemsReadItemsErrors];

export type itemsReadItemsResponses = {
    /**
     * Successful Response
     */
    200: ItemsPublic;
};

export type itemsReadItemsResponse = itemsReadItemsResponses[keyof itemsReadItemsResponses];

export type itemsCreateItemData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type itemsCreateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsCreateItemError = itemsCreateItemErrors[keyof itemsCreateItemErrors];

export type itemsCreateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsCreateItemResponse = itemsCreateItemResponses[keyof itemsCreateItemResponses];

export type itemsDeleteItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsDeleteItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsDeleteItemError = itemsDeleteItemErrors[keyof itemsDeleteItemErrors];

export type itemsDeleteItemResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type itemsDeleteItemResponse = itemsDeleteItemResponses[keyof itemsDeleteItemResponses];

export type itemsReadItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsReadItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemError = itemsReadItemErrors[keyof itemsReadItemErrors];

export type itemsReadItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsReadItemResponse = itemsReadItemResponses[keyof itemsReadItemResponses];

export type itemsUpdateItemData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsUpdateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsUpdateItemError = itemsUpdateItemErrors[keyof itemsUpdateItemErrors];

export type itemsUpdateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsUpdateItemResponse = itemsUpdateItemResponses[keyof itemsUpdateItemResponses];

export type handoversReadHandoversData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Status
         */
        status?: HandoverStatus | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/handovers/';
};

export type handoversReadHandoversErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type handoversReadHandoversError = handoversReadHandoversErrors[keyof handoversReadHandoversErrors];

export type handoversReadHandoversResponses = {
    /**
     * Successful Response
     */
    200: HandoversPublic;
};

export type handoversReadHandoversResponse = handoversReadHandoversResponses[keyof handoversReadHandoversResponses];

export type handoversUploadHandoverData = {
    body: Body_handovers_upload_handover;
    path?: never;
    query?: never;
    url: '/api/v1/handovers/';
};

export type handoversUploadHandoverErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type handoversUploadHandoverError = handoversUploadHandoverErrors[keyof handoversUploadHandoverErrors];

export type handoversUploadHandoverResponses = {
    /**
     * Successful Response
     */
    202: HandoverPublic;
};

export type handoversUploadHandoverResponse = handoversUploadHandoverResponses[keyof handoversUploadHandoverResponses];

export type handoversDiscardHandoverData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/handovers/{id}';
};

export type handoversDiscardHandoverErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type handoversDiscardHandoverError = handoversDiscardHandoverErrors[keyof handoversDiscardHandoverErrors];

export type handoversDiscardHandoverResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type handoversDiscardHandoverResponse = handoversDiscardHandoverResponses[keyof handoversDiscardHandoverResponses];

export type handoversReadHandoverData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/handovers/{id}';
};

export type handoversReadHandoverErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type handoversReadHandoverError = handoversReadHandoverErrors[keyof handoversReadHandoverErrors];

export type handoversReadHandoverResponses = {
    /**
     * Successful Response
     */
    200: HandoverDetailPublic;
};

export type handoversReadHandoverResponse = handoversReadHandoverResponses[keyof handoversReadHandoverResponses];

export type handoversDeleteCardData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
        /**
         * Card Id
         */
        card_id: string;
    };
    query?: never;
    url: '/api/v1/handovers/{id}/patients/{card_id}';
};

export type handoversDeleteCardErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type handoversDeleteCardError = handoversDeleteCardErrors[keyof handoversDeleteCardErrors];

export type handoversDeleteCardResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type handoversDeleteCardResponse = handoversDeleteCardResponses[keyof handoversDeleteCardResponses];

export type handoversUpdateCardData = {
    body: HandoverPatientUpdate;
    path: {
        /**
         * Id
         */
        id: string;
        /**
         * Card Id
         */
        card_id: string;
    };
    query?: never;
    url: '/api/v1/handovers/{id}/patients/{card_id}';
};

export type handoversUpdateCardErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type handoversUpdateCardError = handoversUpdateCardErrors[keyof handoversUpdateCardErrors];

export type handoversUpdateCardResponses = {
    /**
     * Successful Response
     */
    200: HandoverPatientPublic;
};

export type handoversUpdateCardResponse = handoversUpdateCardResponses[keyof handoversUpdateCardResponses];

export type handoversRetryHandoverData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/handovers/{id}/retry';
};

export type handoversRetryHandoverErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type handoversRetryHandoverError = handoversRetryHandoverErrors[keyof handoversRetryHandoverErrors];

export type handoversRetryHandoverResponses = {
    /**
     * Successful Response
     */
    202: HandoverPublic;
};

export type handoversRetryHandoverResponse = handoversRetryHandoverResponses[keyof handoversRetryHandoverResponses];

export type handoversConfirmHandoverData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/handovers/{id}/confirm';
};

export type handoversConfirmHandoverErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type handoversConfirmHandoverError = handoversConfirmHandoverErrors[keyof handoversConfirmHandoverErrors];

export type handoversConfirmHandoverResponses = {
    /**
     * Successful Response
     */
    200: HandoverDetailPublic;
};

export type handoversConfirmHandoverResponse = handoversConfirmHandoverResponses[keyof handoversConfirmHandoverResponses];

export type dashboardReadDashboardData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/dashboard/';
};

export type dashboardReadDashboardResponses = {
    /**
     * Successful Response
     */
    200: DashboardPublic;
};

export type dashboardReadDashboardResponse = dashboardReadDashboardResponses[keyof dashboardReadDashboardResponses];

export type tasksAcknowledgeTaskData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/tasks/{id}/acknowledge';
};

export type tasksAcknowledgeTaskErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tasksAcknowledgeTaskError = tasksAcknowledgeTaskErrors[keyof tasksAcknowledgeTaskErrors];

export type tasksAcknowledgeTaskResponses = {
    /**
     * Successful Response
     */
    200: TaskPublic;
};

export type tasksAcknowledgeTaskResponse = tasksAcknowledgeTaskResponses[keyof tasksAcknowledgeTaskResponses];

export type tasksCompleteTaskData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/tasks/{id}/complete';
};

export type tasksCompleteTaskErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tasksCompleteTaskError = tasksCompleteTaskErrors[keyof tasksCompleteTaskErrors];

export type tasksCompleteTaskResponses = {
    /**
     * Successful Response
     */
    200: TaskPublic;
};

export type tasksCompleteTaskResponse = tasksCompleteTaskResponses[keyof tasksCompleteTaskResponses];

export type tasksCancelTaskData = {
    body: TaskCancel;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/tasks/{id}/cancel';
};

export type tasksCancelTaskErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tasksCancelTaskError = tasksCancelTaskErrors[keyof tasksCancelTaskErrors];

export type tasksCancelTaskResponses = {
    /**
     * Successful Response
     */
    200: TaskPublic;
};

export type tasksCancelTaskResponse = tasksCancelTaskResponses[keyof tasksCancelTaskResponses];

export type flagsAcknowledgeFlagData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/flags/{id}/acknowledge';
};

export type flagsAcknowledgeFlagErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type flagsAcknowledgeFlagError = flagsAcknowledgeFlagErrors[keyof flagsAcknowledgeFlagErrors];

export type flagsAcknowledgeFlagResponses = {
    /**
     * Successful Response
     */
    200: FlagPublic;
};

export type flagsAcknowledgeFlagResponse = flagsAcknowledgeFlagResponses[keyof flagsAcknowledgeFlagResponses];

export type patientsReadPatientsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Include Discharged
         */
        include_discharged?: boolean;
    };
    url: '/api/v1/patients/';
};

export type patientsReadPatientsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type patientsReadPatientsError = patientsReadPatientsErrors[keyof patientsReadPatientsErrors];

export type patientsReadPatientsResponses = {
    /**
     * Successful Response
     */
    200: PatientsPublic;
};

export type patientsReadPatientsResponse = patientsReadPatientsResponses[keyof patientsReadPatientsResponses];

export type patientsCreatePatientData = {
    body: PatientCreate;
    path?: never;
    query?: never;
    url: '/api/v1/patients/';
};

export type patientsCreatePatientErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type patientsCreatePatientError = patientsCreatePatientErrors[keyof patientsCreatePatientErrors];

export type patientsCreatePatientResponses = {
    /**
     * Successful Response
     */
    200: PatientPublic;
};

export type patientsCreatePatientResponse = patientsCreatePatientResponses[keyof patientsCreatePatientResponses];

export type patientsReadPatientData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/patients/{id}';
};

export type patientsReadPatientErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type patientsReadPatientError = patientsReadPatientErrors[keyof patientsReadPatientErrors];

export type patientsReadPatientResponses = {
    /**
     * Successful Response
     */
    200: PatientPublic;
};

export type patientsReadPatientResponse = patientsReadPatientResponses[keyof patientsReadPatientResponses];

export type patientsUpdatePatientData = {
    body: PatientUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/patients/{id}';
};

export type patientsUpdatePatientErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type patientsUpdatePatientError = patientsUpdatePatientErrors[keyof patientsUpdatePatientErrors];

export type patientsUpdatePatientResponses = {
    /**
     * Successful Response
     */
    200: PatientPublic;
};

export type patientsUpdatePatientResponse = patientsUpdatePatientResponses[keyof patientsUpdatePatientResponses];

export type patientsDischargePatientData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/patients/{id}/discharge';
};

export type patientsDischargePatientErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type patientsDischargePatientError = patientsDischargePatientErrors[keyof patientsDischargePatientErrors];

export type patientsDischargePatientResponses = {
    /**
     * Successful Response
     */
    200: PatientPublic;
};

export type patientsDischargePatientResponse = patientsDischargePatientResponses[keyof patientsDischargePatientResponses];

export type patientsReadPatientRecordData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/patients/{id}/record';
};

export type patientsReadPatientRecordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type patientsReadPatientRecordError = patientsReadPatientRecordErrors[keyof patientsReadPatientRecordErrors];

export type patientsReadPatientRecordResponses = {
    /**
     * Successful Response
     */
    200: PatientRecordPublic;
};

export type patientsReadPatientRecordResponse = patientsReadPatientRecordResponses[keyof patientsReadPatientRecordResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];
