/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutHandoversIndexRouteImport } from './routes/_layout/handovers/index'
import { Route as LayoutHandoversHandoverIdRouteImport } from './routes/_layout/handovers/$handoverId'
import { Route as LayoutHandoversNewRouteImport } from './routes/_layout/handovers/new'
import { Route as LayoutPatientsIndexRouteImport } from './routes/_layout/patients/index'
import { Route as LayoutPatientsPatientIdRouteImport } from './routes/_layout/patients/$patientId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHandoversIndexRoute = LayoutHandoversIndexRouteImport.update({
  id: '/handovers/',
  path: '/handovers/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHandoversHandoverIdRoute =
  LayoutHandoversHandoverIdRouteImport.update({
    id: '/handovers/$handoverId',
    path: '/handovers/$handoverId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutHandoversNewRoute = LayoutHandoversNewRouteImport.update({
  id: '/handovers/new',
  path: '/handovers/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPatientsIndexRoute = LayoutPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPatientsPatientIdRoute = LayoutPatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/settings': typeof LayoutSettingsRoute
  '/handovers/$handoverId': typeof LayoutHandoversHandoverIdRoute
  '/handovers/new': typeof LayoutHandoversNewRoute
  '/patients/$patientId': typeof LayoutPatientsPatientIdRoute
  '/handovers/': typeof LayoutHandoversIndexRoute
  '/patients/': typeof LayoutPatientsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/handovers/$handoverId': typeof LayoutHandoversHandoverIdRoute
  '/handovers/new': typeof LayoutHandoversNewRoute
  '/patients/$patientId': typeof LayoutPatientsPatientIdRoute
  '/handovers': typeof LayoutHandoversIndexRoute
  '/patients': typeof LayoutPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/handovers/$handoverId': typeof LayoutHandoversHandoverIdRoute
  '/_layout/handovers/new': typeof LayoutHandoversNewRoute
  '/_layout/patients/$patientId': typeof LayoutPatientsPatientIdRoute
  '/_layout/handovers/': typeof LayoutHandoversIndexRoute
  '/_layout/patients/': typeof LayoutPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/settings'
    | '/handovers/$handoverId'
    | '/handovers/new'
    | '/patients/$patientId'
    | '/handovers/'
    | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/settings'
    | '/'
    | '/handovers/$handoverId'
    | '/handovers/new'
    | '/patients/$patientId'
    | '/handovers'
    | '/patients'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/handovers/$handoverId'
    | '/_layout/handovers/new'
    | '/_layout/patients/$patientId'
    | '/_layout/handovers/'
    | '/_layout/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/handovers/': {
      id: '/_layout/handovers/'
      path: '/handovers'
      fullPath: '/handovers/'
      preLoaderRoute: typeof LayoutHandoversIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/handovers/$handoverId': {
      id: '/_layout/handovers/$handoverId'
      path: '/handovers/$handoverId'
      fullPath: '/handovers/$handoverId'
      preLoaderRoute: typeof LayoutHandoversHandoverIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/handovers/new': {
      id: '/_layout/handovers/new'
      path: '/handovers/new'
      fullPath: '/handovers/new'
      preLoaderRoute: typeof LayoutHandoversNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/patients/': {
      id: '/_layout/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof LayoutPatientsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/patients/$patientId': {
      id: '/_layout/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof LayoutPatientsPatientIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutHandoversHandoverIdRoute: typeof LayoutHandoversHandoverIdRoute
  LayoutHandoversNewRoute: typeof LayoutHandoversNewRoute
  LayoutPatientsPatientIdRoute: typeof LayoutPatientsPatientIdRoute
  LayoutHandoversIndexRoute: typeof LayoutHandoversIndexRoute
  LayoutPatientsIndexRoute: typeof LayoutPatientsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutHandoversHandoverIdRoute: LayoutHandoversHandoverIdRoute,
  LayoutHandoversNewRoute: LayoutHandoversNewRoute,
  LayoutPatientsPatientIdRoute: LayoutPatientsPatientIdRoute,
  LayoutHandoversIndexRoute: LayoutHandoversIndexRoute,
  LayoutPatientsIndexRoute: LayoutPatientsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
